### ISSUE TITLE
Improve CIO Posting

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/jobs#1]
[Here's the post](https://github.com/NYCPlanning/jobs/blob/gh-pages/_posts/2016-04-11-chief-information-officer.MD)

@dannyfuchs welcome to your first github issue chain!  We can use this thread to discuss improvements to the CIO job listing.

cc/ @AmandaDoyle

**Comment by dannyfuchs** [comment]
@chriswhong Sweet. Do you want to make the posting sexier or tweet out as it? If you want to sexy it up, I suggest (forgive me) pasting your recommended text into an email that I can send to Jon and Dana...

cc/ @AmandaDoyle 

PS - What a joy this form of communication is...

**Comment by chriswhong** [comment]
I'll take a crack at it tomorrow morning.  Will send changes in email
before modifying the markdown

**Comment by chriswhong** [comment]
I created an edit branch and issues a pull request.  The repo is private so only members of the github org can see the proposed changes and read the comments.
